### ISSUE TITLE
Concattabs consistantly fails to merge/concate mulitple tabs

### ISSUE THREAD

**Issue by arky** [CJWorkbench/concattabs#2]
A strange bug in concattabs that adds an extract column. Here is a workflow example here: You can see the first step in 'Data Output' tab. 

https://app.workbenchdata.com/workflows/86730

![image](https://user-images.githubusercontent.com/808895/89532224-a4462b00-d81b-11ea-9f13-57fea7b60bf7.png)

**Comment by adamhooper** [comment]
Great catch! Thank you! On it.

**Comment by adamhooper** [comment]
The column `FIPS Code ` in the `M-O` tab has a space at the end. So those two column names are different.

Workbench makes it easy to make this mistake. We'll ponder how we can best improve it. In the meantime, if you nix the extra space from the column name in the `M-O` tab, you should get the outcome you expect.

**Comment by arky** [comment]
Thanks @adamhooper I thought I had a cleaned that data. :(
